### PR TITLE
Added read .rpp functionality to Project class.

### PR DESCRIPTION
**Pull request by jdchart**

### CODE REVIEW

**Comment by jdchart** [comment]
Don't know if this is something you're interested in? Perhaps not perfect yet, and surely some terrible python faux-pas, but it works!

**Comment by jdchart** [comment]
functionality:

```
rpp_file = '/Users/macbook/Documents/mycoolproject.RPP'
myProject = Project(file = rpp_file)
myProject.print()
```

or 

```
myProject = Project()
myProject.read(rpp_file)
myProject.print()
```

And you can continue to add to it and stuff like normal.

**Comment by jamesb93** [comment]
So to summarise, is this essentially the inverse of constructing a file and generating the appropriate structure? So you can parse a file into a bunch of Python objects?

**Comment by jdchart** [comment]
> So to summarise, is this essentially the inverse of constructing a file and generating the appropriate structure? So you can parse a file into a bunch of Python objects?

Exactly, allowing you to edit a project within reathon.

**Comment by jdchart** [comment]
My personal end goal is to be able to use sklearn stuff in conjunction with reacoma, and have things build themselves in place: for example replacing the items i want on a new track with sound from other corpora.

**Comment by jdchart** [comment]
I had started in Max, which is where most of the wierd, javascript-adapted code came from. this is going to be 100x better.

**Comment by jdchart** [comment]
And thanks for the leg work - i look at your python code and weep from its elegance

**Comment by jamesb93** [comment]
> And thanks for the leg work - i look at your python code and weep from its elegance

thanks :)

**Comment by jamesb93** [comment]
So far I really like what it is doing but need to dig into the implementation more. I've started changing some low hanging fruit, like not duplicating functions where it was unnecessary. Instead of relying on the return of `add_single` you can just store the object which you intended to add in a variable (which you were doing anyway). One less function to maintain :)

I'm going to dig through the more knotty code and think about how it might be generalised to work across all the nodes of a REAPER file.

**Comment by jamesb93** [comment]
OMG Plugins are a nightmare because they don't hold all of their information between tags 😱 

```
    <FXCHAIN
      WNDRECT 399 63 813 812
      SHOW 0
      LASTSEL 2
      DOCKED 0
      BYPASS 0 0 0
      <VST "VST3: MEqualizer (MeldaProduction)" MEqualizer.vst3 0 "" 928022665{4D656C646170726F4D4165334D416533} ""
        iYBQN+5e7f4CAAAAAQAAAAAAAAACAAAAAAAAAAIAAAABAAAAAAAAAAIAAAAAAAAAtgMAAAEAAAAAABAA
        0wEAAAEAAAB42n1TXW+bMBR9z6+wvNcVbIzBkYCqrdLtodGiUrXboxucYNWxGZgl3a/fBZql67qJB2TOh++595KdH3YG/VBtp53NMQ0IRsquXaXtNse935wJfF7MsuXi
        ey+N/glE5T2AHfoAdIyunPWtMwaAhZWPRlU5Bo9Fpb1rSxDkOE3IR84jjG5uy8Zo79UIUNATGr/9HOWYsQSjpTzcXH+5NG79NNkwcFgqYHVXcJ9sOlWVcFJurGNl+q22
        d86ZR9n+JozQ/THdPKIJIbjIJpuoyB505etlkZWub9cKrVq10QawMT3BYZGFR0p4FM2yT61s6iJrnLYe+ecGivust/VKdh1GX4cuximEpnEED0bfcnwG7/CoeN0nYEcB
        5YKmkeCRoP9hcZGkcQwcJk4sQFhAKGeUp2Q+5//UsyCOmRApqGEU77JOScpamc2LTKRRzAVPwH7sxxR+ll20SnbDlPQOxnPr9t3Q7HBArDTPsCmUoXLnnK+t6gAkAeEY
        TZ2GPBg9aFu5/d10q7QWBvN6AHAaS7w2cttdgnkMszwM3WWEkmgOaZNkKOl9WvyWFv5pfrEip/TDAin5NEZAZe32sEGuvZemVy+xsvAUCzKGf/8QxewXmCoAY9MBAAAA
        AAAAeNp9U11vmzAUfc+vsLzXFWyMwZGAqq3S7aHRolK126MbnGDVsRmYJd2v3wWapeu6iQdkzofvufeSnR92Bv1QbaedzTENCEbKrl2l7TbHvd+cCXxezLLl4nsvjf4J
        ROU9gB36AHSMrpz1rTMGgIWVj0ZVOQaPRaW9a0sQ5DhNyEfOI4xubsvGaO/VCFDQExq//RzlmLEEo6U83Fx/uTRu/TTZMHBYKmB1V3CfbDpVlXBSbqxjZfqttnfOmUfZ
        /iaM0P0x3TyiCSG4yCabqMgedOXrZZGVrm/XCq1atdEGsDE9wWGRhUdKeBTNsk+tbOoia5y2HvnnBor7rLf1SnYdRl+HLsYphKZxBA9G33J8Bu/wqHjdJ2BHAeWCppHg
        kaD/YXGRpHEMHCZOLEBYQChnlKdkPuf/1LMgjpkQKahhFO+yTknKWpnNi0ykUcwFT8B+7McUfpZdtEp2w5T0DsZz6/bd0OxwQKw0z7AplKFy55yvreoAJAHhGE2dhjwY
        PWhbuf3ddKu0FgbzegBwGku8NnLbXYJ5DLM8DN1lhJJoDmmTZCjpfVr8lhb+aX6xIqf0wwIp+TRGQGXt9rBBrr2XplcvsbLwFAsyhn//EMXsF5gqAGM=
        ADAAEAAAAA==
      >
      PRESETNAME 0
      FLOATPOS 0 0 0 0
      FXID {518A736C-E66E-9248-917E-741DE08C27F4}
      WAK 0 0
      BYPASS 0 0 0
```

I this example I believe parsed correctly, `PRESETNAME 0` belongs to the `FXCHAIN` but is denoted by its position being between the plugins >:(

**Comment by jdchart** [comment]
> So far I really like what it is doing but need to dig into the implementation more. I've started changing some low hanging fruit, like not duplicating functions where it was unnecessary. Instead of relying on the return of `add_single` you can just store the object which you intended to add in a variable (which you were doing anyway). One less function to maintain :)

Very true, I don't know why I didn't do what you have - perhaps wanting to be too slick and get the added node in the same line as adding it to the array or whatever I did.

> OMG Plugins are a nightmare because they don't hold all of their information between tags 😱

This shouldn't be a problem? The way I've tried to implement it is that when you go back down the hierarchy at the end of a tag, the node that props are being appended to becomes the parent again. So it should go up a level, add to VST, then go back down and add to FXchain again? Or have I misunderstood what you're saying?

Also worth noting the 2 current known bugs for parsing in this PR so it's clear:
- When it encounters a prop belonging to an illegal node it adds it to the parent for some reason (at least this is the case for Project(), which means that when you open the created file in Reaper it complains about the project not understanding the chunks that belonged to metronome and stuff)
- Doesn't yet parse the props that are given at the beginning of a chunk (Project: Reaper version, OS etc; Track: {the ID i think}.

Neither of these stop it from working, but will need to be addressed for the perfectionist in me.

**Comment by jdchart** [comment]
Bug 1 fixed

**Comment by jdchart** [comment]
Bug 2 fixed 

So now need to note that there are two reserved kwargs when creating any node: 
- `node_name` (this is when creating a generic node, will be used as the name)
- `meta_props` (this is the properties that are declared with the chunk)

**Comment by jdchart** [comment]
Now in a state where if you read and write a file, the output is identical (including indentation). Only difference is that all of a chunk's props are listed before any child chunks.

**Comment by jdchart** [comment]
Changed get_child, get_track, get_item to plural versions, as nodes can now have multiple types of children. the get_children method creates an array of the given class (by default Node, set to Track and Item when called by get_tracks, get_items). So now typical workflow would be:

```
myProject = Project(file = rpp_file)

for i in range(100):
    myProject.add(Track())

myProject.get_tracks()[50].add(Item(length=5, position=1.5))
```

Noticed bug when I tried this before and the item was added to track 44 - it's because it was counting things like metronome as children!

**Comment by jamesb93** [comment]
Nice!

I think that parallel to this PR we should invent some way of testing if the outputs do the things they promise. One test might be:

Read -> Write -> Read -> Check.

Otherwise its a lot of stabs in the dark and ifs/buts

**Comment by jdchart** [comment]
> I think that parallel to this PR we should invent some way of testing if the outputs do the things they promise. One test might be:

I agree. I shoudl first try and refactor some of my horseshit code, exibit a:

```
this_spaceing = ''
this_spaceing_props = ''
for i in range(this_level):
    this_spaceing = this_spaceing + '  '
for i in range(this_level + 1):
    this_spaceing_props = this_spaceing_props + '  '
```

**Comment by jamesb93** [comment]
I don't want to shame you, but that code deserves the naughty corner.

**Comment by jdchart** [comment]
image

**Comment by jamesb93** [comment]
https://github.com/jamesb93/reathon/pull/3/commits/53c1a8706b5eda3a8ce7a97e53494a0abfe5cd82 avoid making props a class unless you really need to. If you can justify it in text form here go for it but otherwise better to keep it as a list.

**Pull request closed without merging**
